### ISSUE TITLE
Checkbox in Block Editor nicht sichtbar

### ISSUE THREAD

**Issue by ellenbauer** [deworg/dewp-planet-feed#15]
Seit dem neusten Elmastudio Update kann ich die Checkbox bei den Beiträgen nicht mehr finden. Ist das Plugin noch aktiv? Ich habe die Version 1.0.0 istalliert, WordPress 5.8 und Gutenberg 11.3.0. Könnte eventuell das Gutenberg-Plugin schuld sein?

**Comment by 2ndkauboy** [comment]
Ich hatte das gleiche Problem und mir zeitweise damit beholfen, dass ich das Post-Meta manuell hinzuzufügen. Ich glaube ich hatte es so gelöst, dass ich es hier noch einmal als ZIP-Datei runtergeladen und die installierte Version ersetzt habe. Zumindest funktioniert es bei mit seit ein paar Wochen wieder.

**Comment by florianbrinkmann** [comment]
Ich habe gerade mal getestet und sowohl mit 5.8 ohne als auch mit Gutenberg-Plugin wird die Checkbox bei mir angezeigt. Hast du dir die Version über die Releases-Seite runtergeladen (https://github.com/deworg/dewp-planet-feed/releases)? Der direkte Download des Repos funktioniert nicht, weil die Build-Dateien nicht Teil des Repos sind sondern nur für die Release-Pakete erzeugt werden.

**Comment by ellenbauer** [comment]
@florianbrinkmann @2ndkauboy Super, herzlichen Dank für eure Hilfe. Der Download des Releases war die Lösung bei mir. Ich hatte kurzzeitig vergessen, dass ich das Plugin wieder aktivieren wollte, aber jetzt bin ich froh, dass es klappt :)

**Comment by florianbrinkmann** [comment]
Okay, cool, dass es jetzt funktioniert :)

**Comment by Perun** [comment]
Danke für den Hinweis Florian. 👍

Jetzt funktioniert es auch bei mir im Gutenberg-Modus. Musste mit der 0.5.x-er Version immer auf classic umsteigen.
