### ISSUE TITLE
Support for CPT

### ISSUE THREAD

**Issue by obstschale** [deworg/dewp-planet-feed#2]
Until now, the plugin only supports `post` as post type. Thus only posts can be added to the custom feed. But what do you think to support CPTs?

To put this in context: I recently published a new podcast, which is a custom post type. I think the episode would be a good fit for planet but I cannot add it to the planet feed because it is a Would CPT.

Do you think it is a good idea to allow CPTs for this plugin? I could think of a simple setting to activate / deactivate CPTs for this plugin.

**Comment by krafit** [comment]
There's a hook for that :)

**Comment by obstschale** [comment]
Thx. Thus this issue is closed.
