### ISSUE TITLE
After changing the permalink, publication again 

### ISSUE THREAD

**Issue by hagege** [deworg/dewp-planet-feed#21]
I published a new post a few days ago, which is also displayed on Planet.
After I changed the permalink, this post is published again with the new permalink, so that the post is shown in the widget with both the old permalink and the new permalink. The same post is therefore displayed twice.

**Comment by florianbrinkmann** [comment]
I would say that is not issue of the planet feed plugin, it just creates a feed with the posts marked with the checkbox. I don’t know how the plugin that aggregates the feed for the widget works exactly, maybe it just checks for the URL, so thinks it is a not-yet imported post, if the URL is changed. To prevent it, you would need to manually uncheck the box before changing the URL.

**Comment by hagege** [comment]
thanks for info.
