### ISSUE TITLE
Prefix Titles w/ Blog Name

### ISSUE THREAD

**Issue by obstschale** [deworg/dewp-planet-feed#3]
Hey,

the english planet feed prefixes all titles with the blog name. You see in the screenshot below "WPTavern:" and "Post Status:". I think it would be nice to have this feature also for our planet feed.

However, @2ndkauboy already mentioned that it should be an option b/c some blogs may have long names.

What do you think?

<img width="631" alt="bildschirmfoto 2016-04-24 um 17 45 29" src="https://cloud.githubusercontent.com/assets/1058710/14768507/a1e8a184-0a44-11e6-9a70-c06fd20f3945.png">

**Comment by krafit** [comment]
You can filter `the_title_rss` to prefix it with a custom string. Or: there's a hook for that :)

**Comment by obstschale** [comment]
Thx. Thus this issue is closed.
