### ISSUE TITLE
Support für Gutenberg

### ISSUE THREAD

**Issue by Perun** [deworg/dewp-planet-feed#4]
Hallo zusammen,

ich habe gerade Gutenberg getestet und dabei ist mir aufgefallen, dass das "DEWP Planet Feed" im Gutenberg nicht zu sehen ist. Wollte euch nur Bescheid geben.

Grüße

**Comment by glueckpress** [comment]
Danke fürs Bescheid sagen, @Perun! Hoffe, jemand hat einen Nerv sich darum zu kümmern; bis ich mich da rein gearbeitet hätte, wäre Gutenberg wahrscheinlich schon wieder Gutenstaub.

**Comment by florianbrinkmann** [comment]
Ich versuche mich mal dran.

**Comment by florianbrinkmann** [comment]
Ich hab jetzt einen Stand, der funktionieren sollte.

So sieht es aus:

![gutenberg-dewp-planet-feed](https://user-images.githubusercontent.com/2310924/44219154-a240b880-a17b-11e8-8d35-91854d45d6d6.gif)

Es braucht jetzt Webpack, deshalb ist es mit Runterladen vom Repo alleine nicht mehr getan – ich hab fürs Testen mal eine ZIP erstellt [dewp-planet-feed.zip](https://github.com/deworg/dewp-planet-feed/files/2294272/dewp-planet-feed.zip). @Perun könntest du einmal testen, ob das so funktioniert? Falls ja, würde ich dann einen PR erstellen (die gemachten Änderungen können hier schon mal angeschaut werden: https://github.com/florianbrinkmann/dewp-planet-feed/commit/e4eaa7a3ec9f1e78c59e827b37a26022d620df98).

@glueckpress soll ich dann noch eine Travis-CI-Integration bauen, damit bei einem Release eine Installations-fertige ZIP auf der GitHub-Releases-Page erstellt wird (so wie hier die lazy-loading-responsive-images.zip-Dateien https://github.com/florianbrinkmann/lazy-loading-responsive-images/releases)? Wäre ja vermutlich das einfachste.

Ich konnte leider nicht den Meta-Key mit Unterstrich vorne verwenden, da ich den über die REST-API nicht aktualisieren darf (irgendwas mit Berechtigungen). Habe ihn jetzt also zusätzlich einmal ohne Unterstrich eingeführt.

**Comment by glueckpress** [comment]
Das Repo ist deins, @florianbrinkmann! 🤗

**Comment by florianbrinkmann** [comment]
All right! :)

**Comment by Perun** [comment]
Danke Florian (@florianbrinkmann) und auch Caspar (@glueckpress), es wird in meiner Testumgebung auf jeden Fall angezeigt. Werde es nachher auch auf perun.net ausprobieren ob der Übertrag in den Feed auch wirklich klappt.

**Comment by Perun** [comment]
Jetzt hat auch der Übertrag in den dt. Planet-Feed geklappt. Noch einmal vielen Dank.

**Comment by florianbrinkmann** [comment]
Super, danke für’s Testen @Perun! Dann werde ich mich mal um einen Release mit der Anpassung kümmern.

**Comment by florianbrinkmann** [comment]
Der Release ist gemacht und an sich sollte auch alles so eingestellt sein, dass das GitHub-Updater-Plugin sich die ZIP holt, die Travis für den Release erstellt hat. Momentan scheint er aber noch die 0.4 zu holen, vielleicht ist es aber auch nur irgendwo gecacht. Ich beobachte das erst mal noch ein bisschen.

**Comment by florianbrinkmann** [comment]
Nach Aktualisieren des GitHub-Updater-Caches hat er 0.5.0 registriert. Problem jetzt ist nur, dass das Update von 0.4.0 auf 0.5.0 nicht korrekt die Release-ZIP nutzt sondern direkt das Repo, weil der entsprechende Plugin-Header logischerweise erst mit 0.5.0 eingefügt wurde, das Plugin also nicht weiß, dass es 0.5.0 von dem Release-Asset holen soll.

Lösung: Manuell die Version in der `dewp-planet-feed.php` von 0.5.0 auf 0.4.0 ändern und dann das Update noch mal installieren, dann zieht er es korrekt.
