### ISSUE TITLE
Checkbox in Gutenberg nicht vorhanden

### ISSUE THREAD

**Issue by Perun** [deworg/dewp-planet-feed#6]
Hallo zusammen, leider ist zumindest seit Gutenberg 3.9.0 die Checkbox verschwunden. Ob die schon bei Gutenberg 3.8.0 weg war kann ich nicht sagen, da ich in der Zeit nicht veröffentlicht habe. /c @florianbrinkmann

**Comment by florianbrinkmann** [comment]
Hi @Perun, danke für die Info, ich werde versuchen mir das die Tage anzuschauen.

**Comment by Perun** [comment]
Hallo Florian (@florianbrinkmann) hattest du Zeit dir das Problem anzuschauen?

**Comment by florianbrinkmann** [comment]
Hi Vladimir, leider bisher nicht, ich setze es mir für’s Wochenende auf die Liste!

**Comment by florianbrinkmann** [comment]
Ich hab es noch auf dem Schirm, bin umzugsbedingt aber momentan leider etwas knapp an Zeit und hab es am WE nicht geschafft, sorry … Sobald ich eine freie Stunde habe, schaue ich es mir an!

**Comment by florianbrinkmann** [comment]
Hi @Perun,

ich habe soeben eine 0.5.1 veröffentlicht, die mit der aktuellen Gutenberg-Version funktionieren sollte. Falls es damit weiter Probleme gibt bitte einfach das Issue wieder aufmachen beziehungsweise einfach hier wieder kommentieren :)

Viele Grüße
Florian

**Comment by Perun** [comment]
Hallo Florian, leider ist es mit Gutenberg 4.4.0 nicht kompatibel. /c @florianbrinkmann

**Comment by glueckpress** [comment]
Ich glaube, es macht Sinn, bis zum letzen 5.0 RC zu warten, das ist ja die reinste Sisyphus-Nummer.

**Comment by florianbrinkmann** [comment]
Jop, klingt nach nem guten Plan. @Perun was genau meinst du mit nicht kompatibel? Ich habe auf meiner Site 4.4.0 installiert und sehe die Checkbox (und sie funktioniert auch).

**Comment by florianbrinkmann** [comment]
Habe gerade auf Gutenberg 4.5.0 aktualisiert und scheint soweit immer noch alles zu funktionieren. Schließe das hiermit dann erst mal wieder.
